spring:
  application:
    name: Demo
  datasource:
    url: jdbc:mysql://localhost:3306/frontend?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: p@ssw0rd
  data:
    rest:
      base-path: /rest/api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 7080
  servlet:
    context-path: /
